#!/bin/bash

set -e
cd ~
rm -f bin/*

for a in opt/*-*; do
    p="${a%%-*}"
    if [[ -L "$p" ]]; then
       v=$(readlink "$p")

       if [[ "$v" != *"$a" ]]; then
       	  rm -rf "$a"
       fi
    fi
done
